name: Tests MultiBrowser

on:  
  workflow_dispatch:
    inputs:
      spec: 
        description: Run by cypress command line
        default: yarn cypress run
jobs:
  cypress-e2e-electron:
    runs-on: unbutu-latest
    steps:
      - name: Get code
        uses: actions/checkout@v3.5.3
      
      - name: Cypress run
        uses: cypress-io/github-action@v5.8.2
        with:
          install-command: yarn install
          browser: electron
          record: true
          group: UI Electron
          spec: ${{ github.inputs.spec }}
        
      
