name: Run Basic Tests - WalkDog

on:
  pull_request:
    branches: [main]

jobs: 
  cypress-run:
    runs-on: ubuntu-latest
      
    steps: 
      - name: Checkout the project
        uses: actions/checkout@v3

      - name: Install project dependencies
        uses: yarn install

      

      
      