name: Tests

on:  
  workflow_dispatch:

jobs:
  cypress-run-electron:
    runs-on: ubuntu-22.04
    container: cypress/browsers:node16.16.0-chrome107-ff107-edge
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Cypress run
        uses: cypress-io/github-action@v5
        with:
          build: npm run build
          start: npm start
          browser: electron
      - name: Tests run
        run: yarn cypress run
  cypress-run-chrome:
    runs-on: ubuntu-22.04
    container: cypress/browsers:node16.16.0-chrome107-ff107-edge
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Cypress run
        uses: cypress-io/github-action@v5
        with:
          build: npm run build
          start: npm start
          browser: chrome
      - name: Tests run
        run: yarn cypress run
  cypress-run-firefox:
    runs-on: ubuntu-22.04
    container: cypress/browsers:node16.16.0-chrome107-ff107-edge
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Cypress run
        uses: cypress-io/github-action@v5
        with:
          build: npm run build
          start: npm start
          browser: firefox
      - name: Tests run
        run: yarn cypress run
