name: Run Basic Tests - WalkDog

on:
  pull_request:
    branches: [main]

jobs: 
  cypress-run:
    runs-on: unbutu-latest
      
    steps: 
      - name: Checkout the project
        uses: actions/checkout@v4

      - name: Install project dependencies
        uses: yarn install

      - name: Run tests
        uses: cypress-io/github-action@v6
        with: 
          record: true

      

      
      